# upload-task.ps1 - generated by setup; template fallback if setup has not run
param()

$ErrorActionPreference = 'Stop'
$Workspace = $PSScriptRoot
$ReposDir = Join-Path $Workspace 'repos'
$CompletedDir = Join-Path $Workspace 'completed'

function Test-ProtectedBranch([string]$Name) {
    return ($Name.Trim().ToLowerInvariant() -in @('main', 'master'))
}

Write-Host '[auto] Upload completed backlog task' -ForegroundColor Cyan

if (-not (Test-Path $CompletedDir)) {
    Write-Host '[auto] No completed/ folder - nothing to upload' -ForegroundColor Yellow
    exit 0
}

$tasks = @()
foreach ($json in Get-ChildItem $CompletedDir -Filter '*.json' -ErrorAction SilentlyContinue) {
    try {
        $t = Get-Content -LiteralPath $json.FullName -Raw | ConvertFrom-Json
        if ($t.status -ne 'completed') { continue }
        if (-not $t.repo_path -or -not $t.branch) { continue }
        $tasks += $t
    } catch { }
}

if ($tasks.Count -eq 0) {
    Write-Host '[auto] No completed tasks ready for upload' -ForegroundColor Yellow
    exit 0
}

Write-Host ''
for ($i = 0; $i -lt $tasks.Count; $i++) {
    $t = $tasks[$i]
    Write-Host "  [$($i + 1)] $($t.title) -> $($t.branch)" -ForegroundColor Gray
}

Write-Host ''
$pick = Read-Host 'Pick task number (or empty to abort)'
if ([string]::IsNullOrWhiteSpace($pick)) {
    Write-Host 'Aborted.' -ForegroundColor Yellow
    exit 0
}

$idx = [int]$pick - 1
if ($idx -lt 0 -or $idx -ge $tasks.Count) {
    Write-Host 'Invalid selection' -ForegroundColor Red
    exit 1
}

$chosen = $tasks[$idx]
$repoPath = Join-Path $Workspace ($chosen.repo_path -replace '/', '\')
$branch = [string]$chosen.branch

if (Test-ProtectedBranch $branch) {
    Write-Host "[auto] Refusing protected branch: $branch" -ForegroundColor Red
    exit 1
}

if (-not (Test-Path -LiteralPath $repoPath)) {
    Write-Host "[auto] Repo path missing: $repoPath" -ForegroundColor Red
    exit 1
}

Push-Location $repoPath
try {
    $cur = (& git symbolic-ref --short HEAD 2>$null).Trim()
    if ($cur -ne $branch) {
        Write-Host "[auto] Checking out $branch ..." -ForegroundColor DarkGray
        & git checkout $branch
    }

    Write-Host ''
    Write-Host "  repo:   $repoPath" -ForegroundColor Gray
    Write-Host "  branch: $branch" -ForegroundColor Gray
    & git status --short
    Write-Host ''
    Write-Host '  Type confirm to push to origin (anything else aborts)' -ForegroundColor Yellow
    $typed = Read-Host '  >'

    if ($typed.Trim().ToLowerInvariant() -ne 'confirm') {
        Write-Host 'Aborted - no push.' -ForegroundColor Yellow
        exit 0
    }

    Write-Host "[auto] Pushing origin/$branch ..." -ForegroundColor Cyan
    & git push -u origin $branch
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    Write-Host '[auto] Pushed. Open a PR manually on GitHub.' -ForegroundColor Green
} finally {
    Pop-Location
}
